### PR TITLE
Update node page with basic info

### PR DESCRIPTION
**Pull request by HongPong**
Based on content from https://www.drupal.org/project/entity and https://www.drupal.org/node/49768 mainly as well as http://drupal.stackexchange.com/questions/78325/how-to-create-a-new-properties-to-node-or-user-and-so-on

Just really wanted to get something basic up on the board for nodes. Best regards!

### CODE REVIEW

**Comment by rhuffstedtler** [comment]
To my mind this is potentially good info, but it doesn't quite follow the format we've been using elsewhere. Seems to me that you really need to build off the entity and fields chapters and focus on a teardown of node.module.

As an aside, that's one of the reasons I started on a module chapter, so we can make the transition between talking about the core functionality that is implemented in includes vs. what is impelemented in modules that ship as part of core. Feel free to jump in on that one if you need it to cover something that you have a dependency on.

**Comment by crittermike** [comment]
Yeah, seems like this PR is more "useful info for devs to know about nodes" as opposed to "how does the node module work" so it goes against the grain like @rhuffstedtler said, but maybe that's OK for a temporary starting point to this chapter? 

Even if we just use this as a jumping off point (for example, we could perhaps use that list of node properties as a checklist of things that we need to explain how they get added to the node object), I don't have a problem with us merging this and altering as needed for the node chapter.  It gives us a place to start and a new contributor. :D 

What do you think @rhuffstedtler?

@HongPong huge thanks for the PR! Hope to see more of you!

**Comment by HongPong** [comment]
Thanks for the feedback, much appreciated. I didn't have the time today to approach it from a deeper level, but I figure to get this chapter started it's very relevant to know what the properties of nodes are, and how to add another property correctly. I'd been mulling over posting this for a couple weeks, even though it's just a small fragment of the info you'd want to have in this chapter.

Later, "How the node module works" could probably open the chapter, and after that, "here's what properties a node has" and then "how to add another property" - something like that would probably be effective for people.

**Comment by rhuffstedtler** [comment]
Yep - I'm fine with including it. Just wanted to make sure Dan has a plan for getting into the gory details. :-)

Should probably mark it as under construction for consumers. I don't have a great example of where we've done that, because you went back and finished all the things that you had half done.

**Comment by crittermike** [comment]
Yeah, I just put a big bold "THIS CHAPTER IS NOT COMPLETE!" at the top -
nothing fancy.

Awesome, seems like we all agree then. I'm going to go ahead and merge. You
both rock immensely.

**Pull request merged**
